package(default_visibility = ["//visibility:public"])

filegroup(
    name = "IosProjects",
    srcs = glob(["**"]) + [
        "//IOS/ios/app1:app1",
        "//IOS/ios/app2:app2",
        "//IOS/ios/app3:app3",
        "//IOS/ios/app4:app4",
        "//IOS/ios/app5:app5",
        "//IOS/ios/app6:app6",
        "//IOS/ios/app7:app7",
        "//IOS/ios/app8:app8",
        "//IOS/ios/app9:app9",
        "//IOS/ios/app10:app10",
        "//IOS/ios/atom1:atom1",
        "//IOS/ios/atom2:atom2",
        "//IOS/ios/atom3:atom3",
        "//IOS/ios/atom4:atom4",
        "//IOS/ios/molecule1:molecule1",
        "//IOS/ios/molecule2:molecule2",
        "//IOS/ios/molecule3:molecule3",
        "//IOS/ios/molecule4:molecule4",
        "//IOS/ios/organisme1:organisme1",
        "//IOS/ios/organisme2:organisme2",
        "//IOS/ios/organisme3:organisme3",
        "//IOS/ios/organisme4:organisme4"
    ],
)
