package(default_visibility = ["//visibility:public"])

load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

licenses(["notice"])

swift_library(
    name = "organisme4",
    srcs = [
        "Sources/Organisme4.swift",
    ]
)

