package(default_visibility = ["//visibility:public"])

filegroup(
    name = "project",
    srcs = glob(["**"]) + [
        "//Android/appAndroid1/src/main:bazel_app1",
        "//Android/appAndroid2/src/main:bazel_app2",
        "//Android/appAndroid3/src/main:bazel_app3",
        "//Android/appAndroid4/src/main:bazel_app4",
        "//Android/appAndroid5/src/main:bazel_app5",
        "//Android/appAndroid6/src/main:bazel_app6",
        "//Android/appAndroid7/src/main:bazel_app7",
        "//Android/appAndroid8/src/main:bazel_app8",
        "//Android/appAndroid9/src/main:bazel_app9",
        "//Android/appAndroid10/src/main:bazel_app10", 
        "//Android/organismeAndroid1/src/main:bazel_organisme1_library",
        "//Android/organismeAndroid2/src/main:bazel_organisme2_library",
        "//Android/organismeAndroid3/src/main:bazel_organisme3_library",
        "//Android/organismeAndroid4/src/main:bazel_organisme4_library",
        "//Android/moleculeAndroid1/src/main:bazel_molecule1_library",
        "//Android/moleculeAndroid2/src/main:bazel_molecule2_library",
        "//Android/moleculeAndroid3/src/main:bazel_molecule3_library",
        "//Android/moleculeAndroid4/src/main:bazel_molecule4_library",
        "//Android/atomAndroid1/src/main:bazel_atom1_library",
        "//Android/atomAndroid2/src/main:bazel_atom2_library",
        "//Android/atomAndroid3/src/main:bazel_atom3_library",
        "//Android/atomAndroid4/src/main:bazel_atom4_library",
    ],
)