package(default_visibility = ["//visibility:public"])

load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

licenses(["notice"])

swift_library(
    name = "molecule2",
    srcs = [
        "Sources/Molecule2.swift",
    ]
)

